version: "3.8"

services:
  cats-api-db:
    image: mysql
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: $DATABASE_PASSWORD
      MYSQL_DATABASE: $DATABASE_NAME
    ports:
      - $DATABASE_PORT:$DATABASE_PORT
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql

  cats-api-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: node
    depends_on:
      - cats-api-db
    stdin_open: true
    tty: true

volumes:
  db-config:
  db-data:
